### PR TITLE
Added the de2 Board

### PR DESCRIPTION
**Pull request by erdmannp**
I dont had any problems with that. I think it should be merged into "production" repository.

### CODE REVIEW

**Comment by fjullien** [comment]
Hi,

Could you please clean-up your commit history ? You could squash all commits together.

Franck.

**Comment by fjullien** [comment]
Ok, now you need to clean-up your commit message.
Something like "systems: add Altera de2 board port" is enough.

Franck.

PS: When you update your branch, please leave a comment here. If you don't do that, we don't receive any notification.

**Comment by olofk** [comment]
Hi,

I agree with @fjullien. It's a great addition to have support for the de2 board, but please squash it into a single patch so that it's easier to see what's going on in the repository

**Comment by olofk** [comment]
This is superseded by #95

**Pull request closed without merging**
